from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def load_ocr_pages(output_dir: Path) -> list[dict]:
    candidates = [
        output_dir / "ocr_pages.json",
        output_dir / "pages.json",
    ]

    for path in candidates:
        if not path.exists():
            continue

        data = json.loads(path.read_text(encoding="utf-8"))

        if isinstance(data, dict):
            pages = data.get("pages") or data.get("items") or []
        elif isinstance(data, list):
            pages = data
        else:
            pages = []

        usable = []

        for idx, page in enumerate(pages, start=1):
            if not isinstance(page, dict):
                continue

            page_number = page.get("page_number") or page.get("pdf_page") or idx
            text = str(page.get("text") or page.get("content") or "").strip()

            usable.append(
                {
                    "page_number": int(page_number),
                    "text": text,
                }
            )

        if usable:
            return usable

    return []


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"-\n(?=[a-zăâîșț])", "", text, flags=re.IGNORECASE)
    return text.strip()


def is_noise_page(text: str) -> bool:
    compact = re.sub(r"\s+", " ", text).strip()
    lower = compact.lower()

    if len(compact) < 250:
        return True

    noise_hits = 0

    for token in [
        "cuprins",
        "isbn",
        "coordonator",
        "editura",
        "tehnoredactare",
        "autori",
        "bibliografie",
    ]:
        if token in lower:
            noise_hits += 1

    # Cuprins / front matter pages often have many short lines and dotted page references.
    dotted_refs = len(re.findall(r"\.{3,}\s*\d+", text))

    if noise_hits >= 2:
        return True

    if "cuprins" in lower and dotted_refs >= 5:
        return True

    return False


def clean_title_candidate(line: str) -> str:
    line = re.sub(r"\s+", " ", line).strip(" -–—:;,.")
    line = re.sub(r"^[|Il1]+\s*", "", line).strip()
    return line


def infer_title(text: str, fallback: str) -> str:
    lines = [
        clean_title_candidate(line)
        for line in text.splitlines()
        if clean_title_candidate(line)
    ]

    bad = {
        "cuprins",
        "bibliografie",
        "manualul de instalații",
        "manualul de instalatii",
    }

    for line in lines[:30]:
        lower = line.lower()

        if lower in bad:
            continue

        if len(line) < 8 or len(line) > 120:
            continue

        if re.fullmatch(r"[\d\s.]+", line):
            continue

        # Prefer numbered technical headings.
        if re.match(r"^\d+(?:\.\d+)*\.?\s+\S+", line):
            return line

    for line in lines[:20]:
        lower = line.lower()

        if lower in bad:
            continue

        if 10 <= len(line) <= 90 and not re.fullmatch(r"[\d\s.]+", line):
            return line

    return fallback


def chunk_pages(pages: list[dict], min_page: int, pages_per_lesson: int) -> list[dict]:
    filtered = []

    for page in pages:
        number = int(page["page_number"])
        text = normalize_text(page["text"])

        if number < min_page:
            continue

        if is_noise_page(text):
            continue

        filtered.append(
            {
                "page_number": number,
                "text": text,
            }
        )

    chunks = []

    for i in range(0, len(filtered), pages_per_lesson):
        group = filtered[i : i + pages_per_lesson]

        if not group:
            continue

        text = "\n\n".join(item["text"] for item in group)
        pages_list = [item["page_number"] for item in group]

        title = infer_title(
            text,
            fallback=f"Pages {pages_list[0]}–{pages_list[-1]}",
        )

        chunks.append(
            {
                "title": title,
                "pages": pages_list,
                "text": text,
            }
        )

    return chunks


def write_course(output_dir: Path, pdf_name: str, chunks: list[dict]) -> None:
    lines = [
        f"# {Path(pdf_name).stem}",
        "",
        "Generated by Voila! OCR course builder.",
        "",
        "Mode: source language, OCR text, no AI generation.",
        "",
        "Text status: Tesseract OCR reading text; original scan preserved in source PDF.",
        "",
    ]

    outline = []

    for idx, chunk in enumerate(chunks, start=1):
        lesson_id = f"L{idx:03d}"
        title = chunk["title"]
        pages = chunk["pages"]
        text = chunk["text"]
        word_count = len(text.split())

        outline.append(
            {
                "lesson_id": lesson_id,
                "title": title,
                "source_pdf_pages": pages,
                "word_count": word_count,
            }
        )

        lines.extend(
            [
                f"## {lesson_id} — {title}",
                "",
                f"Source PDF pages: {', '.join(str(p) for p in pages)}",
                "",
                f"Word count: {word_count}",
                "",
                "### Cleaned source text",
                "",
                "```text",
                text,
                "```",
                "",
            ]
        )

    course_md = "\n".join(lines).strip() + "\n"

    (output_dir / "course.md").write_text(course_md, encoding="utf-8")
    (output_dir / "course.cleaned.md").write_text(course_md, encoding="utf-8")

    (output_dir / "course_outline.json").write_text(
        json.dumps(
            {
                "version": "ocr_course_builder_v0.1",
                "lesson_count": len(chunks),
                "lessons": outline,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    outline_md = ["# Course outline", ""]

    for item in outline:
        outline_md.append(f"- {item['lesson_id']} — {item['title']}")

    (output_dir / "course_outline.md").write_text(
        "\n".join(outline_md) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Voila course from OCR pages")
    parser.add_argument("output_dir")
    parser.add_argument("--pdf-name", default="")
    parser.add_argument("--min-page", type=int, default=15)
    parser.add_argument("--pages-per-lesson", type=int, default=2)
    parser.add_argument("--max-lessons", type=int, default=260)

    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()

    pages = load_ocr_pages(output_dir)

    if not pages:
        raise FileNotFoundError(f"No OCR pages found in {output_dir}")

    chunks = chunk_pages(
        pages=pages,
        min_page=args.min_page,
        pages_per_lesson=args.pages_per_lesson,
    )

    chunks = chunks[: args.max_lessons]

    pdf_name = args.pdf_name or output_dir.name + ".pdf"

    write_course(output_dir, pdf_name, chunks)

    print("Voila! OCR course generated successfully.")
    print(f"Pages loaded: {len(pages)}")
    print(f"Lessons generated: {len(chunks)}")
    print(f"- {output_dir / 'course.cleaned.md'}")


if __name__ == "__main__":
    main()
