from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OCR_SCRIPT = PROJECT_ROOT / "services" / "api" / "ocr_tesseract_pages.py"


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def get_pages(data: object) -> list[dict]:
    if isinstance(data, dict):
        pages = data.get("pages") or data.get("items") or []
        return pages if isinstance(pages, list) else []

    if isinstance(data, list):
        return data

    return []


def text_length_from_pages_json(path: Path) -> int:
    if not path.exists():
        return 0

    try:
        data = read_json(path)
    except Exception:
        return 0

    total = 0

    for page in get_pages(data):
        if isinstance(page, dict):
            total += len(str(page.get("text") or page.get("content") or "").strip())

    return total


def normalize_pages_shape(existing: object, ocr_pages: list[dict]) -> object:
    if isinstance(existing, dict):
        if "pages" in existing:
            existing["pages"] = ocr_pages
            existing["text_source"] = "tesseract_ocr"
            return existing

        if "items" in existing:
            existing["items"] = ocr_pages
            existing["text_source"] = "tesseract_ocr"
            return existing

    if isinstance(existing, list):
        return ocr_pages

    return {
        "text_source": "tesseract_ocr",
        "pages": ocr_pages,
    }


def write_pages_md(path: Path, pdf_name: str, ocr_pages: list[dict]) -> None:
    lines = [
        f"# OCR pages for {pdf_name}",
        "",
        "Generated by Voila! OCR gate.",
        "",
    ]

    for page in ocr_pages:
        number = page.get("page_number") or page.get("pdf_page") or ""
        text = str(page.get("text") or page.get("content") or "").strip()

        lines.append(f"## Page {number}")
        lines.append("")
        lines.append(text)
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def restore_existing_ocr(pdf_path: Path, output_dir: Path) -> bool:
    ocr_pages_path = output_dir / "ocr_pages.json"

    if not ocr_pages_path.exists():
        return False

    raw = read_json(ocr_pages_path)
    ocr_pages = get_pages(raw)

    if not ocr_pages:
        return False

    pages_json = output_dir / "pages.json"
    pages_md = output_dir / "pages.md"

    if pages_json.exists():
        existing = read_json(pages_json)

        backup = output_dir / "pages.before_ocr_gate.json"
        if not backup.exists():
            backup.write_text(pages_json.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        existing = {}

    replaced = normalize_pages_shape(existing, ocr_pages)

    pages_json.write_text(
        json.dumps(replaced, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    if pages_md.exists():
        backup_md = output_dir / "pages.before_ocr_gate.md"
        if not backup_md.exists():
            backup_md.write_text(pages_md.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")

    write_pages_md(pages_md, pdf_path.name, ocr_pages)

    return True


def run_tesseract_ocr(
    pdf_path: Path,
    output_dir: Path,
    lang: str,
    psm: int,
    zoom: float,
) -> None:
    cmd = [
        sys.executable,
        str(OCR_SCRIPT),
        str(pdf_path),
        str(output_dir),
        "--lang",
        lang,
        "--psm",
        str(psm),
        "--zoom",
        str(zoom),
        "--replace-pages",
    ]

    print("Running OCR:")
    print(" ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(PROJECT_ROOT),
        text=True,
    )

    if result.returncode != 0:
        raise SystemExit(result.returncode)


def main() -> None:
    parser = argparse.ArgumentParser(description="Voila! OCR gate for scanned PDFs")
    parser.add_argument("pdf")
    parser.add_argument("output_dir")
    parser.add_argument("--min-text-chars", type=int, default=800)
    parser.add_argument("--lang", default="ron+eng")
    parser.add_argument("--psm", type=int, default=1)
    parser.add_argument("--zoom", type=float, default=2.0)
    parser.add_argument("--run-ocr", action="store_true")

    args = parser.parse_args()

    pdf_path = Path(args.pdf).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    pages_json = output_dir / "pages.json"
    before_chars = text_length_from_pages_json(pages_json)

    print("Voila! OCR gate")
    print(f"PDF: {pdf_path}")
    print(f"Text chars before OCR gate: {before_chars}")
    print(f"Minimum required chars: {args.min_text_chars}")

    action = "skip"

    if before_chars >= args.min_text_chars:
        print("OCR gate skipped: extracted text is sufficient.")
    else:
        print("OCR gate triggered: extracted text is too weak.")

        if restore_existing_ocr(pdf_path, output_dir):
            action = "restored_existing_ocr"
            print("Existing OCR restored into pages.json/pages.md.")
        elif args.run_ocr:
            action = "ran_tesseract_ocr"
            run_tesseract_ocr(
                pdf_path=pdf_path,
                output_dir=output_dir,
                lang=args.lang,
                psm=args.psm,
                zoom=args.zoom,
            )
        else:
            action = "no_existing_ocr"
            print("No existing OCR found. Run with --run-ocr to OCR this PDF.")

    after_chars = text_length_from_pages_json(pages_json)

    report = {
        "version": "voila_ocr_gate_v0.1",
        "source_file": str(pdf_path),
        "min_text_chars": args.min_text_chars,
        "chars_before": before_chars,
        "chars_after": after_chars,
        "action": action,
    }

    report_path = output_dir / "ocr_gate_report.json"
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"Text chars after OCR gate: {after_chars}")
    print(f"Action: {action}")
    print(f"- {report_path}")


if __name__ == "__main__":
    main()
