from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import time
from pathlib import Path

import fitz
from PIL import Image, ImageOps


def find_tesseract() -> str:
    found = shutil.which("tesseract")

    if found:
        return found

    candidates = [
        r"C:\Program Files\Tesseract-OCR\tesseract.exe",
        r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe",
    ]

    for candidate in candidates:
        if Path(candidate).exists():
            return candidate

    raise FileNotFoundError(
        "Tesseract not found. Install it with: winget install -e --id UB-Mannheim.TesseractOCR"
    )


def render_page(page: fitz.Page, out_path: Path, zoom: float) -> None:
    pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
    image = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

    # Light preprocessing: grayscale + contrast normalization.
    image = ImageOps.grayscale(image)
    image = ImageOps.autocontrast(image)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(out_path)


def run_tesseract(
    tesseract: str,
    image_path: Path,
    lang: str,
    psm: int,
    tessdata_prefix: str | None,
) -> tuple[str, float, int]:
    env = os.environ.copy()

    if tessdata_prefix:
        env["TESSDATA_PREFIX"] = tessdata_prefix

    cmd = [
        tesseract,
        str(image_path),
        "stdout",
        "-l",
        lang,
        "--oem",
        "1",
        "--psm",
        str(psm),
    ]

    start = time.time()

    result = subprocess.run(
        cmd,
        text=True,
        capture_output=True,
        env=env,
        encoding="utf-8",
        errors="replace",
    )

    elapsed = time.time() - start

    if result.returncode != 0:
        raise RuntimeError(
            f"Tesseract failed for {image_path}\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )

    text = (result.stdout or "").replace("\f", "").strip()

    return text, elapsed, result.returncode


def normalize_pages_shape(existing: object, ocr_pages: list[dict]) -> object:
    if isinstance(existing, dict):
        if "pages" in existing:
            existing["pages"] = ocr_pages
            existing["text_source"] = "tesseract_ocr"
            return existing

        if "items" in existing:
            existing["items"] = ocr_pages
            existing["text_source"] = "tesseract_ocr"
            return existing

    if isinstance(existing, list):
        return ocr_pages

    return {
        "text_source": "tesseract_ocr",
        "pages": ocr_pages,
    }


def write_pages_md(path: Path, pdf_path: Path, ocr_pages: list[dict]) -> None:
    parts = [
        f"# OCR pages for {pdf_path.name}",
        "",
        "Generated by Voila! Tesseract OCR pipeline.",
        "",
    ]

    for page in ocr_pages:
        number = page["page_number"]
        text = page.get("text") or ""

        parts.append(f"## Page {number}")
        parts.append("")
        parts.append(text)
        parts.append("")

    path.write_text("\n".join(parts), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Voila! local Tesseract OCR for scanned PDFs")
    parser.add_argument("pdf", help="Source PDF path")
    parser.add_argument("output_dir", help="Voila output directory")
    parser.add_argument("--lang", default="ron+eng")
    parser.add_argument("--psm", type=int, default=1)
    parser.add_argument("--zoom", type=float, default=2.0)
    parser.add_argument("--page-from", type=int, default=1)
    parser.add_argument("--page-to", type=int, default=0)
    parser.add_argument("--replace-pages", action="store_true")
    parser.add_argument("--tessdata-prefix", default="")

    args = parser.parse_args()

    pdf_path = Path(args.pdf).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not pdf_path.exists():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    tesseract = find_tesseract()

    tessdata_prefix = args.tessdata_prefix.strip() or os.environ.get("TESSDATA_PREFIX")

    images_dir = output_dir / "ocr" / "page_images"
    ocr_pages = []
    report_pages = []

    doc = fitz.open(pdf_path)

    print("Voila! OCR started.")
    print(f"PDF: {pdf_path}")
    print(f"Pages: {len(doc)}")
    print(f"Lang: {args.lang}")
    print(f"PSM: {args.psm}")
    print(f"Zoom: {args.zoom}")
    print(f"Tesseract: {tesseract}")

    if tessdata_prefix:
        print(f"TESSDATA_PREFIX: {tessdata_prefix}")

    page_from = max(1, args.page_from)
    page_to = min(len(doc), args.page_to if args.page_to > 0 else len(doc))

    print(f"Page range: {page_from}-{page_to}")

    for index in range(page_from, page_to + 1):
        page = doc[index - 1]
        image_path = images_dir / f"page_{index:04d}.png"

        render_page(page, image_path, args.zoom)

        print(f"OCR page {index}/{len(doc)}...")

        text, elapsed, returncode = run_tesseract(
            tesseract=tesseract,
            image_path=image_path,
            lang=args.lang,
            psm=args.psm,
            tessdata_prefix=tessdata_prefix,
        )

        ocr_pages.append(
            {
                "page_number": index,
                "text": text,
                "text_source": "tesseract_ocr",
                "ocr_lang": args.lang,
            }
        )

        report_pages.append(
            {
                "page_number": index,
                "chars": len(text),
                "words": len(text.split()),
                "seconds": round(elapsed, 2),
                "image": str(image_path),
                "returncode": returncode,
            }
        )

    doc.close()

    ocr_json = output_dir / "ocr_pages.json"
    ocr_md = output_dir / "ocr_pages.md"
    report_json = output_dir / "ocr_report.tesseract.json"

    ocr_json.write_text(
        json.dumps(
            {
                "version": "voila_tesseract_ocr_v0.1",
                "source_file": str(pdf_path),
                "lang": args.lang,
                "psm": args.psm,
                "zoom": args.zoom,
                "pages": ocr_pages,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    write_pages_md(ocr_md, pdf_path, ocr_pages)

    report_json.write_text(
        json.dumps(
            {
                "version": "voila_tesseract_ocr_v0.1",
                "source_file": str(pdf_path),
                "page_count": len(ocr_pages),
                "total_chars": sum(item["chars"] for item in report_pages),
                "total_words": sum(item["words"] for item in report_pages),
                "pages": report_pages,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    if args.replace_pages:
        pages_json = output_dir / "pages.json"
        pages_md = output_dir / "pages.md"

        if pages_json.exists():
            backup = output_dir / "pages.before_ocr.json"
            if not backup.exists():
                backup.write_text(pages_json.read_text(encoding="utf-8"), encoding="utf-8")

            try:
                existing = json.loads(pages_json.read_text(encoding="utf-8"))
            except Exception:
                existing = {}

            replaced = normalize_pages_shape(existing, ocr_pages)

            pages_json.write_text(
                json.dumps(replaced, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

        else:
            pages_json.write_text(
                json.dumps({"text_source": "tesseract_ocr", "pages": ocr_pages}, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

        if pages_md.exists():
            backup = output_dir / "pages.before_ocr.md"
            if not backup.exists():
                backup.write_text(pages_md.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")

        write_pages_md(pages_md, pdf_path, ocr_pages)

    print("")
    print("Voila! OCR complete.")
    print(f"- {ocr_json}")
    print(f"- {ocr_md}")
    print(f"- {report_json}")

    if args.replace_pages:
        print("- pages.json/pages.md replaced with OCR text")


if __name__ == "__main__":
    main()
