from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROMANIAN_FIXES = {
    "instalatile": "instalațiile",
    "instalatii": "instalații",
    "instalaţii": "instalații",
    "protectia": "protecția",
    "protectiei": "protecției",
    "tensiunea": "tensiunea",
    "luminos": "luminos",
    "iluminat": "iluminat",
    "functie": "funcție",
    "funcţie": "funcție",
    "mărimi": "mărimi",
    "masurarea": "măsurarea",
    "măsurarea": "măsurarea",
    "curentului": "curentului",
    "rezistente": "rezistențe",
    "rezistenţei": "rezistenței",
    "rezistenței": "rezistenței",
    "electrica": "electrică",
    "electrică": "electrică",
    "electrice": "electrice",
    "automatizari": "automatizări",
    "automatizări": "automatizări",
    "sincron": "sincron",
    "asincron": "asincron",
}


def load_pages(path: Path) -> tuple[object, list[dict]]:
    data = json.loads(path.read_text(encoding="utf-8"))

    if isinstance(data, dict):
        pages = data.get("pages") or data.get("items") or []
    elif isinstance(data, list):
        pages = data
    else:
        pages = []

    return data, pages


def normalize_symbols(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("˚", "°").replace("º", "°")
    text = text.replace("…", "...")
    text = text.replace("“", '"').replace("”", '"').replace("„", '"')
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("—", " - ").replace("–", " - ")
    text = text.replace("ﬁ", "fi").replace("ﬂ", "fl")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def fix_common_ocr_words(text: str) -> str:
    def replace_word(match: re.Match) -> str:
        word = match.group(0)
        fixed = ROMANIAN_FIXES.get(word.lower())

        if not fixed:
            return word

        if word[:1].isupper():
            return fixed[:1].upper() + fixed[1:]

        return fixed

    return re.sub(r"\b[\wăâîșțĂÂÎȘȚţşŢŞ]+\b", replace_word, text)


def is_junk_line(line: str) -> bool:
    value = line.strip()

    if not value:
        return True

    if re.fullmatch(r"\d{1,4}", value):
        return True

    if re.fullmatch(r"[|Il1\s._-]{1,8}", value):
        return True

    if len(value) <= 2:
        return True

    # OCR artifacts / broken table leaders.
    if len(value) < 12 and re.search(r"[_|]{2,}", value):
        return True

    return False


def is_heading_like(line: str) -> bool:
    value = line.strip()

    if re.match(r"^\d+(?:\.\d+){0,5}\.?\s+\S+", value):
        return True

    if re.match(r"^(fig\.|figura)\s+", value, flags=re.IGNORECASE):
        return True

    if value.isupper() and 6 <= len(value) <= 90:
        return True

    return False


def merge_lines(text: str) -> str:
    raw_lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in raw_lines if not is_junk_line(line)]

    paragraphs = []
    current = ""

    for line in lines:
        line = re.sub(r"-\s*$", "", line)

        if is_heading_like(line):
            if current:
                paragraphs.append(current.strip())
                current = ""
            paragraphs.append(line)
            continue

        if not current:
            current = line
            continue

        # Continue same paragraph if previous line did not end sentence.
        if not re.search(r"[.!?:;)]$", current):
            current += " " + line
        else:
            paragraphs.append(current.strip())
            current = line

    if current:
        paragraphs.append(current.strip())

    text = "\n\n".join(paragraphs)
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    text = re.sub(r"([({\[])\s+", r"\1", text)
    text = re.sub(r"\s+([)}\]])", r"\1", text)
    text = re.sub(r"\b([A-Za-zĂÂÎȘȚăâîșț])\s+([.,;:])", r"\1\2", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def clean_page_text(text: str) -> str:
    text = normalize_symbols(text)
    text = fix_common_ocr_words(text)
    text = merge_lines(text)
    return text


def write_pages_md(path: Path, pdf_name: str, pages: list[dict]) -> None:
    chunks = [
        f"# OCR cleaned pages for {pdf_name}",
        "",
        "Generated by Voila! OCR text cleaner.",
        "",
    ]

    for page in pages:
        page_number = page.get("page_number") or page.get("pdf_page") or ""
        text = str(page.get("text") or "").strip()

        chunks.extend(
            [
                f"## Page {page_number}",
                "",
                text,
                "",
            ]
        )

    path.write_text("\n".join(chunks), encoding="utf-8")


def replace_shape(original: object, pages: list[dict]) -> object:
    if isinstance(original, dict):
        if "pages" in original:
            original["pages"] = pages
            original["text_source"] = "tesseract_ocr_cleaned"
            return original

        if "items" in original:
            original["items"] = pages
            original["text_source"] = "tesseract_ocr_cleaned"
            return original

    if isinstance(original, list):
        return pages

    return {
        "text_source": "tesseract_ocr_cleaned",
        "pages": pages,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean Voila OCR text")
    parser.add_argument("output_dir")
    parser.add_argument("--replace-pages", action="store_true")
    parser.add_argument("--replace-ocr", action="store_true")

    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()
    ocr_path = output_dir / "ocr_pages.json"

    if not ocr_path.exists():
        raise FileNotFoundError(f"ocr_pages.json not found: {ocr_path}")

    original, pages = load_pages(ocr_path)

    cleaned_pages = []

    for index, page in enumerate(pages, start=1):
        if not isinstance(page, dict):
            continue

        page_number = page.get("page_number") or page.get("pdf_page") or index
        text = str(page.get("text") or page.get("content") or "")

        cleaned = clean_page_text(text)

        new_page = dict(page)
        new_page["page_number"] = int(page_number)
        new_page["text"] = cleaned
        new_page["text_source"] = "tesseract_ocr_cleaned"

        cleaned_pages.append(new_page)

    cleaned_json = output_dir / "ocr_pages.cleaned.json"
    cleaned_md = output_dir / "ocr_pages.cleaned.md"

    cleaned_json.write_text(
        json.dumps(
            {
                "version": "voila_ocr_cleaner_v0.1",
                "page_count": len(cleaned_pages),
                "pages": cleaned_pages,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    write_pages_md(cleaned_md, output_dir.name + ".pdf", cleaned_pages)

    if args.replace_ocr:
        backup = output_dir / "ocr_pages.before_cleaner.json"

        if not backup.exists():
            backup.write_text(ocr_path.read_text(encoding="utf-8"), encoding="utf-8")

        ocr_path.write_text(
            json.dumps(
                {
                    "version": "voila_ocr_cleaner_v0.1",
                    "page_count": len(cleaned_pages),
                    "pages": cleaned_pages,
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )

        write_pages_md(output_dir / "ocr_pages.md", output_dir.name + ".pdf", cleaned_pages)

    if args.replace_pages:
        pages_json = output_dir / "pages.json"
        pages_md = output_dir / "pages.md"

        if pages_json.exists():
            backup = output_dir / "pages.before_ocr_cleaner.json"

            if not backup.exists():
                backup.write_text(pages_json.read_text(encoding="utf-8"), encoding="utf-8")

            try:
                existing = json.loads(pages_json.read_text(encoding="utf-8"))
            except Exception:
                existing = {}
        else:
            existing = {}

        pages_json.write_text(
            json.dumps(replace_shape(existing, cleaned_pages), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        if pages_md.exists():
            backup_md = output_dir / "pages.before_ocr_cleaner.md"

            if not backup_md.exists():
                backup_md.write_text(pages_md.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")

        write_pages_md(pages_md, output_dir.name + ".pdf", cleaned_pages)

    total_chars = sum(len(page.get("text") or "") for page in cleaned_pages)
    total_words = sum(len(str(page.get("text") or "").split()) for page in cleaned_pages)

    print("Voila! OCR text cleaned.")
    print(f"Pages: {len(cleaned_pages)}")
    print(f"Chars: {total_chars}")
    print(f"Words: {total_words}")
    print(f"- {cleaned_json}")
    print(f"- {cleaned_md}")


if __name__ == "__main__":
    main()
