from __future__ import annotations

import argparse
import json
import time
from pathlib import Path


def load_json(path: Path, default):
    if not path.exists():
        return default

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def save_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def normalize_pdf_name(pdf_name: str) -> str:
    return Path(str(pdf_name or "")).name


def output_dir_for_pdf(project_root: Path, pdf_name: str) -> Path:
    safe_pdf = normalize_pdf_name(pdf_name)
    return project_root / "data" / "output" / Path(safe_pdf).stem


def corrections_path(out_dir: Path) -> Path:
    return out_dir / "ocr_corrections.json"


def load_corrections(out_dir: Path) -> dict:
    path = corrections_path(out_dir)
    data = load_json(path, {})

    if isinstance(data, dict):
        data.setdefault("version", "voila_ocr_corrections_v1")
        data.setdefault("page_corrections", {})
        return data

    # Preserve old format if the file was [] or another shape.
    return {
        "version": "voila_ocr_corrections_v1",
        "legacy_value": data,
        "page_corrections": {},
    }


def save_corrections(out_dir: Path, data: dict) -> None:
    save_json(corrections_path(out_dir), data)


def get_page_text(out_dir: Path, page_number: int) -> str:
    for name in ["pages.json", "ocr_pages.json", "ocr_tsv_columns_pages.json", "ocr_body_columns_pages.json"]:
        path = out_dir / name
        payload = load_json(path, None)

        if payload is None:
            continue

        pages = payload.get("pages", []) if isinstance(payload, dict) else payload

        if not isinstance(pages, list):
            continue

        for page in pages:
            try:
                pn = int(page.get("page_number"))
            except Exception:
                continue

            if pn == int(page_number):
                return str(page.get("text") or "")

    return ""


def get_corrected_text(out_dir: Path, page_number: int) -> str:
    data = load_corrections(out_dir)
    item = data.get("page_corrections", {}).get(str(int(page_number)))

    if isinstance(item, dict) and "text" in item:
        return str(item.get("text") or "")

    return get_page_text(out_dir, page_number)


def save_page_correction(
    out_dir: Path,
    page_number: int,
    text: str,
    status: str = "reviewed",
) -> dict:
    data = load_corrections(out_dir)

    key = str(int(page_number))
    now = time.strftime("%Y-%m-%d %H:%M:%S")

    data["page_corrections"][key] = {
        "page_number": int(page_number),
        "text": str(text or ""),
        "status": status,
        "updated_at": now,
        "source": "manual_review",
    }

    data["updated_at"] = now

    save_corrections(out_dir, data)

    return data["page_corrections"][key]


def backup_once(path: Path, suffix: str) -> None:
    if not path.exists():
        return

    backup = path.with_name(path.name + suffix)

    if backup.exists():
        return

    backup.write_text(
        path.read_text(encoding="utf-8", errors="ignore"),
        encoding="utf-8",
    )


def write_pages_md(path: Path, pdf_name: str, payload: dict) -> None:
    pages = payload.get("pages", []) if isinstance(payload, dict) else []

    lines = [
        f"# OCR pages for {pdf_name}",
        "",
        "Generated by Voila! corrected OCR pipeline.",
        "",
    ]

    for page in pages:
        lines.append(f"## Page {page.get('page_number')}")
        lines.append("")
        lines.append(str(page.get("text") or "").strip())
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def apply_corrections_to_payload(payload: dict, corrections: dict) -> tuple[dict, list[int]]:
    pages = payload.get("pages", []) if isinstance(payload, dict) else []

    applied = []

    for page in pages:
        try:
            pn = int(page.get("page_number"))
        except Exception:
            continue

        item = corrections.get(str(pn))

        if not isinstance(item, dict):
            continue

        corrected = str(item.get("text") or "")

        if not corrected.strip():
            continue

        page["text_before_manual_correction"] = str(page.get("text") or "")
        page["text"] = corrected
        page["text_source"] = str(page.get("text_source") or "ocr") + "+manual_correction"
        page["manual_correction_status"] = item.get("status") or "reviewed"
        page["manual_correction_updated_at"] = item.get("updated_at") or ""

        applied.append(pn)

    return payload, applied


def apply_page_corrections(out_dir: Path, pdf_name: str = "") -> dict:
    data = load_corrections(out_dir)
    corrections = data.get("page_corrections", {})

    report = {
        "version": "voila_apply_ocr_corrections_v1",
        "out_dir": str(out_dir),
        "correction_count": len(corrections),
        "targets": [],
        "applied_pages": [],
        "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }

    for name in ["pages.json", "ocr_pages.json"]:
        path = out_dir / name
        payload = load_json(path, None)

        if not isinstance(payload, dict):
            continue

        backup_once(path, ".before_manual_ocr_corrections")

        payload, applied = apply_corrections_to_payload(payload, corrections)

        save_json(path, payload)

        report["targets"].append(name)
        report["applied_pages"].extend(applied)

        md_name = "pages.md" if name == "pages.json" else "ocr_pages.md"
        write_pages_md(out_dir / md_name, pdf_name or out_dir.name, payload)

    report["applied_pages"] = sorted(set(report["applied_pages"]))

    save_json(out_dir / "ocr_manual_corrections_apply_report.json", report)

    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Voila OCR page corrections")
    parser.add_argument("command", choices=["apply"])
    parser.add_argument("out_dir")
    parser.add_argument("--pdf-name", default="")

    args = parser.parse_args()

    out_dir = Path(args.out_dir)

    if args.command == "apply":
        report = apply_page_corrections(out_dir, pdf_name=args.pdf_name)
        print("Voila OCR corrections applied.")
        print("Corrections:", report["correction_count"])
        print("Applied pages:", len(report["applied_pages"]))
        print("Report:", out_dir / "ocr_manual_corrections_apply_report.json")


if __name__ == "__main__":
    main()
