from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

try:
    from content_filter import should_exclude_study_item
except Exception:
    def should_exclude_study_item(**kwargs) -> bool:
        return False


TECHNICAL_KEYWORDS = [
    "se folosește", "se folosesc", "este utilizat", "sunt utilizate", "este destinat",
    "permite", "asigură", "reduce", "mărește", "crește", "scade", "trebuie", "necesar",
    "se recomandă", "se montează", "se alimentează", "funcționează", "comandă",
    "tensiune", "curent", "putere", "flux", "iluminare", "rezistență", "motor",
    "instalație", "protecție", "automatizare", "contact", "releu", "siguranță",
    "is used", "are used", "designed", "must", "should", "requires", "provides",
    "pressure", "temperature", "engine", "pump", "valve", "filter", "system",
]

RO_TOPIC_RULES = [
    ("sisteme de iluminat", ["sistem de iluminat", "sisteme de iluminat", "iluminat interior", "iluminat exterior"]),
    ("mărimi luminotehnice", ["flux luminos", "iluminare", "intensitate luminoasă", "luminanță"]),
    ("instalații electrice", ["instalații electrice", "instalația electrică", "alimentare cu energie"]),
    ("protecții electrice", ["protecție", "siguranță", "descărcări electrice", "supracurent"]),
    ("motoare electrice", ["motor electric", "motoare electrice", "rotor", "stator", "asincron", "sincron"]),
    ("sisteme de comandă automată", ["comandă automată", "releu", "contactor", "automatizare"]),
    ("măsurări electrice", ["măsurarea", "aparat de măsură", "voltmetru", "ampermetru", "wattmetru"]),
    ("surse de lumină", ["lămpi", "lampă", "fluorescente", "incandescență", "vapori de sodiu"]),
    ("corpuri de iluminat", ["corpuri de iluminat", "cil", "armătură de iluminat"]),
]

EN_TOPIC_RULES = [
    ("engine cycles", ["cycle", "diesel cycle", "indicator diagram"]),
    ("fuel injection", ["fuel injection", "injector", "atomized fuel"]),
    ("cooling systems", ["cooling", "coolant"]),
    ("lubricating oil systems", ["lubricating oil", "lube oil"]),
    ("filters and strainers", ["filter", "strainer"]),
    ("marine diesel engines", ["diesel engine", "propulsion", "bore", "stroke"]),
]


BAD_SENTENCE_PATTERNS = [
    r"^figure\s+",
    r"^fig\.\s+",
    r"^figura\s+",
    r"^table\s+",
    r"^tabel\s+",
    r"^\d+$",
    r"^chapter\s+\d+",
    r"^capitolul\s+\d+",
    r"^cuprins\b",
    r"^bibliografie\b",
]


def normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def normalize_key(value: str) -> str:
    return normalize_space(value).lower()


def detect_language(text: str) -> str:
    lower = normalize_key(text)
    ro_markers = [
        " și ", " în ", " este ", " sunt ", " pentru ", " care ", " instala",
        "măsur", "funcție", "tensiune", "curent", "iluminat", "protecție",
        "ă", "î", "ș", "ț", "â",
    ]

    score = sum(1 for marker in ro_markers if marker in lower)

    return "ro" if score >= 2 else "en"


def split_sentences(text: str) -> list[str]:
    text = normalize_space(text)

    if not text:
        return []

    parts = re.split(r"(?<=[.!?])\s+(?=[A-ZĂÂÎȘȚ0-9])", text)
    out = []

    for part in parts:
        sentence = normalize_space(part)

        if 55 <= len(sentence) <= 420:
            out.append(sentence)

    return out


def extract_lessons(course_md: str) -> list[dict]:
    pattern = re.compile(r"^##\s+(L\d+)\s+—\s+(.+?)\s*$", re.MULTILINE)
    matches = list(pattern.finditer(course_md))
    lessons = []

    for idx, match in enumerate(matches):
        lesson_id = match.group(1).strip()
        title = match.group(2).strip()

        start = match.end()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(course_md)
        block = course_md[start:end]

        pages = []
        pages_match = re.search(r"Source PDF pages:\s*([0-9,\s]+)", block)

        if pages_match:
            pages = [
                int(item.strip())
                for item in pages_match.group(1).split(",")
                if item.strip().isdigit()
            ]

        text_match = re.search(
            r"### Cleaned source text\s*```text\s*(.*?)\s*```",
            block,
            flags=re.DOTALL,
        )

        source_text = text_match.group(1).strip() if text_match else block.strip()

        lessons.append(
            {
                "lesson_id": lesson_id,
                "title": title,
                "source_pdf_pages": pages,
                "source_text": source_text,
            }
        )

    return lessons


def sentence_is_bad(sentence: str) -> bool:
    value = normalize_key(sentence)

    for pattern in BAD_SENTENCE_PATTERNS:
        if re.search(pattern, value):
            return True

    bad_fragments = [
        "generated by voila",
        "source pdf pages",
        "word count",
        "isbn",
        "editura",
        "coordonator",
        "tehnoredactare",
        "all rights reserved",
    ]

    if any(fragment in value for fragment in bad_fragments):
        return True

    if len(re.findall(r"[A-Za-zĂÂÎȘȚăâîșț]", sentence)) < 30:
        return True

    return False


def technical_score(sentence: str) -> int:
    lower = normalize_key(sentence)
    score = 0

    for keyword in TECHNICAL_KEYWORDS:
        if keyword in lower:
            score += 1

    if re.search(r"\b\d+(?:[.,]\d+)?\s*(v|kv|a|ma|w|kw|lm|lx|cd|hz|°|%)\b", lower):
        score += 2

    if ";" in sentence:
        score += 1

    if re.search(r"\b(fig\.|figura)\s*[ivxlcdm0-9]", lower):
        score += 1

    return score


def infer_concept_title(lesson_title: str, sentence: str, language: str) -> str:
    lower = normalize_key(sentence + " " + lesson_title)
    rules = RO_TOPIC_RULES if language == "ro" else EN_TOPIC_RULES

    for topic, keywords in rules:
        if any(keyword in lower for keyword in keywords):
            return topic

    title = normalize_space(lesson_title)

    if title:
        return title[:90]

    return "noțiuni tehnice" if language == "ro" else "technical fundamentals"


def question_from_sentence(sentence: str, concept: str, language: str) -> tuple[str, str]:
    lower = normalize_key(sentence)

    if language == "ro":
        if re.search(r"\b(se numește|reprezintă|este definit|se definește)\b", lower):
            return f"Cum definește sursa {concept}?", "definition"

        if re.search(r"\b(se compune|este alcătuit|sunt alcătuite|conține|cuprinde)\b", lower):
            return f"Din ce este alcătuit sau ce cuprinde {concept}?", "components"

        if re.search(r"\b(se folosește|se folosesc|este utilizat|sunt utilizate|servește|rolul)\b", lower):
            return f"Care este rolul sau scopul descris pentru {concept}?", "purpose"

        if re.search(r"\b(trebuie|este necesar|se recomandă|obligatoriu)\b", lower):
            return f"Ce cerință sau recomandare menționează sursa pentru {concept}?", "requirement"

        if re.search(r"\b(când|dacă|în cazul|la pornire|în timpul|pentru)\b", lower):
            return f"În ce situație sau condiții descrie sursa {concept}?", "condition"

        if re.search(r"\b(deoarece|pentru că|astfel|ca urmare|determină|produce)\b", lower):
            return f"Ce cauză, motiv sau efect descrie sursa pentru {concept}?", "cause_effect"

        return f"Ce precizare tehnică face sursa despre {concept}?", "technical_fact"

    if "used" in lower:
        return f"What purpose does the source describe for {concept}?", "purpose"

    if "must" in lower or "should" in lower or "required" in lower:
        return f"What requirement does the source state for {concept}?", "requirement"

    if "when" in lower or "if" in lower or "during" in lower:
        return f"Under what condition does the source describe {concept}?", "condition"

    return f"What technical point does the source state about {concept}?", "technical_fact"


def lesson_passes_page_filter(pages: list[int], min_page: int) -> bool:
    if min_page <= 1:
        return True

    if not pages:
        return False

    return max(pages) >= min_page


def build_questions(lessons: list[dict], max_per_lesson: int, max_total: int, min_page: int) -> list[dict]:
    questions = []

    full_text = "\n".join(lesson.get("source_text") or "" for lesson in lessons)
    course_language = detect_language(full_text)

    for lesson in lessons:
        if len(questions) >= max_total:
            break

        lesson_id = lesson["lesson_id"]
        title = lesson["title"]
        pages = lesson.get("source_pdf_pages", [])
        source_text = lesson.get("source_text") or ""

        if not lesson_passes_page_filter(pages, min_page):
            continue

        if should_exclude_study_item(title=title, source_text=source_text, lesson_id=lesson_id):
            continue

        lesson_language = detect_language(source_text) if source_text else course_language

        candidates = []

        for sentence in split_sentences(source_text):
            if sentence_is_bad(sentence):
                continue

            if should_exclude_study_item(
                title=title,
                question="",
                answer=sentence,
                source_text=sentence,
                lesson_id=lesson_id,
            ):
                continue

            score = technical_score(sentence)

            if score <= 0:
                continue

            concept = infer_concept_title(title, sentence, lesson_language)

            candidates.append(
                {
                    "sentence": sentence,
                    "score": score,
                    "concept": concept,
                    "language": lesson_language,
                }
            )

        candidates.sort(key=lambda item: item["score"], reverse=True)

        used = set()
        lesson_count = 0

        for candidate in candidates:
            if lesson_count >= max_per_lesson or len(questions) >= max_total:
                break

            answer = candidate["sentence"]
            concept = candidate["concept"]
            language = candidate["language"]
            question_text, qtype = question_from_sentence(answer, concept, language)

            key = normalize_key(question_text)

            if key in used:
                continue

            used.add(key)
            qid = f"SQ{len(questions) + 1:04d}"

            questions.append(
                {
                    "question_id": qid,
                    "lesson_id": lesson_id,
                    "concept_id": f"{lesson_id} — {concept}",
                    "concept_title": concept,
                    "lesson_title": title,
                    "question_type": qtype,
                    "language": language,
                    "question": question_text,
                    "answer": answer,
                    "source_pdf_pages": pages,
                    "source_sentence": answer,
                    "generator": "study_quiz_builder_v0.4.0_localized",
                }
            )

            lesson_count += 1

    return questions


def main() -> None:
    parser = argparse.ArgumentParser(description="Voila! localized source-based study quiz builder")
    parser.add_argument("output_dir")
    parser.add_argument("--max-per-lesson", type=int, default=4)
    parser.add_argument("--max-total", type=int, default=500)
    parser.add_argument("--min-page", type=int, default=1)

    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()
    course_path = output_dir / "course.cleaned.md"

    if not course_path.exists():
        raise FileNotFoundError(f"course.cleaned.md not found: {course_path}")

    course_md = course_path.read_text(encoding="utf-8", errors="ignore")
    lessons = extract_lessons(course_md)

    questions = build_questions(
        lessons=lessons,
        max_per_lesson=args.max_per_lesson,
        max_total=args.max_total,
        min_page=args.min_page,
    )

    quiz = {
        "version": "0.4.0",
        "mode": "source_only_localized",
        "generator": "study_quiz_builder_v0.4.0_localized",
        "question_count": len(questions),
        "questions": questions,
    }

    out = output_dir / "quiz.study.json"
    out.write_text(json.dumps(quiz, ensure_ascii=False, indent=2), encoding="utf-8")

    print("Voila! localized study quiz generated successfully.")
    print(f"Lessons parsed: {len(lessons)}")
    print(f"Questions generated: {len(questions)}")
    print(f"- {out}")


if __name__ == "__main__":
    main()
