from pathlib import Path
import re

path = Path("services/api/web_app.py")
text = path.read_text(encoding="utf-8")

# Ensure Form import exists.
text = re.sub(
    r"from fastapi import ([^\n]+)",
    lambda m: (
        "from fastapi import "
        + ", ".join(
            dict.fromkeys(
                [part.strip() for part in m.group(1).split(",")] + ["Form"]
            )
        )
    ),
    text,
    count=1,
)

if '@app.get("/review-ocr-text")' not in text:
    route = r'''

def _load_ocr_review_pages(output_dir: Path) -> list[dict]:
    candidates = [
        output_dir / "ocr_pages.json",
        output_dir / "pages.json",
    ]

    for path in candidates:
        if not path.exists():
            continue

        data = _load_json_file(path, {})

        if isinstance(data, dict):
            pages = data.get("pages") or data.get("items") or []
        elif isinstance(data, list):
            pages = data
        else:
            pages = []

        usable = []

        for idx, page in enumerate(pages, start=1):
            if not isinstance(page, dict):
                continue

            page_number = int(page.get("page_number") or page.get("pdf_page") or idx)
            page_text = str(page.get("text") or page.get("content") or "")

            usable.append(
                {
                    "page_number": page_number,
                    "text": page_text,
                }
            )

        if usable:
            return usable

    return []


def _write_ocr_review_pages(output_dir: Path, pages: list[dict]) -> None:
    payload = {
        "version": "voila_ocr_text_review_v1",
        "text_source": "manual_reviewed_ocr",
        "pages": pages,
    }

    for target_name in ["ocr_pages.json", "pages.json"]:
        target = output_dir / target_name

        if target.exists():
            backup = output_dir / f"{target_name}.before_text_review.json"

            if not backup.exists():
                backup.write_text(target.read_text(encoding="utf-8"), encoding="utf-8")

        _save_json_file(target, payload)

    md_lines = [
        f"# Reviewed OCR pages for {output_dir.name}",
        "",
        "Generated by Voila! OCR Text Review.",
        "",
    ]

    for page in pages:
        md_lines.extend(
            [
                f"## Page {page['page_number']}",
                "",
                str(page.get("text") or "").strip(),
                "",
            ]
        )

    for target_name in ["ocr_pages.md", "pages.md"]:
        target = output_dir / target_name

        if target.exists():
            backup = output_dir / f"{target_name}.before_text_review.md"

            if not backup.exists():
                backup.write_text(target.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")

        target.write_text("\n".join(md_lines), encoding="utf-8")


def _ocr_page_image_url(output_dir: Path, page_number: int) -> str:
    candidates = [
        output_dir / "ocr" / "page_images" / f"page_{page_number:04d}.png",
        output_dir / "scanned_pages" / f"page_{page_number:04d}.jpg",
    ]

    for candidate in candidates:
        if candidate.exists():
            rel = candidate.relative_to(PROJECT_ROOT / "data" / "output")
            return "/output/" + str(rel).replace("\\", "/")

    return ""


def _detect_suspicious_ocr_text(text: str) -> bool:
    value = str(text or "")

    if len(value.strip()) < 80:
        return True

    weird = len(re.findall(r"[�□■◆◇<>~`^|_]{1,}", value))
    letters = len(re.findall(r"[A-Za-zĂÂÎȘȚăâîșț]", value))
    digits = len(re.findall(r"\d", value))

    if weird >= 5:
        return True

    if digits > letters and len(value) > 200:
        return True

    if re.search(r"\b(jj|ixii|v0|01g|lll|iiii|[Il1]{4,})\b", value.lower()):
        return True

    return False


@app.get("/review-ocr-text")
def review_ocr_text(pdf: str = "", page: int = 1):
    from fastapi.responses import HTMLResponse
    from urllib.parse import quote

    pdf_name = _safe_pdf_name(pdf)

    if not pdf_name:
        return HTMLResponse("<h1>Missing PDF name</h1>", status_code=400)

    output_dir = _output_dir_for_pdf_name(pdf_name)
    pages = _load_ocr_review_pages(output_dir)

    if not pages:
        return HTMLResponse("<h1>No OCR pages found</h1><p>Run OCR first.</p>", status_code=404)

    page_numbers = [int(item["page_number"]) for item in pages]
    min_page = min(page_numbers)
    max_page = max(page_numbers)

    if page < min_page:
        page = min_page

    if page > max_page:
        page = max_page

    current = next((item for item in pages if int(item["page_number"]) == page), pages[0])
    current_text = current.get("text") or ""

    suspicious_pages = [
        int(item["page_number"])
        for item in pages
        if _detect_suspicious_ocr_text(item.get("text") or "")
    ]

    previous_page = max(min_page, page - 1)
    next_page = min(max_page, page + 1)
    image_url = _ocr_page_image_url(output_dir, page)

    suspicious_nav = " ".join(
        f'<a href="/review-ocr-text?pdf={quote(pdf_name)}&page={p}">{p}</a>'
        for p in suspicious_pages[:80]
    )

    image_html = (
        f'<img class="scan-img" src="{_html_escape(image_url)}" alt="OCR source page {page}">'
        if image_url
        else '<div class="no-img">No rendered page image found for this page.</div>'
    )

    html_doc = f"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Review OCR Text · Voila!</title>
  <style>
    :root {{
      --bg: #101819;
      --panel: #202d31;
      --panel2: #26363b;
      --text: #f6ead7;
      --muted: #c7ad94;
      --line: #3b4b50;
      --accent: #e0ad68;
      --bad: #b45b46;
    }}

    * {{ box-sizing: border-box; }}

    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: system-ui, -apple-system, Segoe UI, sans-serif;
      padding: 24px;
    }}

    .wrap {{
      max-width: 1700px;
      margin: 0 auto;
    }}

    .top {{
      display: flex;
      justify-content: space-between;
      gap: 16px;
      align-items: center;
      margin-bottom: 18px;
    }}

    h1 {{
      margin: 0;
      font-size: clamp(30px, 5vw, 52px);
      line-height: 1.05;
    }}

    a, button {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 11px 16px;
      background: var(--panel2);
      color: var(--text);
      text-decoration: none;
      font-weight: 850;
      cursor: pointer;
      font-size: 15px;
    }}

    button {{
      background: var(--accent);
      border-color: transparent;
      color: white;
    }}

    .grid {{
      display: grid;
      grid-template-columns: minmax(420px, 0.95fr) minmax(520px, 1.05fr);
      gap: 20px;
      align-items: start;
    }}

    .panel {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 24px;
      padding: 20px;
      box-shadow: 0 18px 48px rgba(0,0,0,0.22);
    }}

    .scan-img {{
      width: 100%;
      max-height: 82vh;
      object-fit: contain;
      background: #f2ead8;
      border-radius: 18px;
      border: 1px solid var(--line);
    }}

    .no-img {{
      padding: 40px;
      border: 1px dashed var(--line);
      border-radius: 18px;
      color: var(--muted);
    }}

    textarea {{
      width: 100%;
      min-height: 68vh;
      resize: vertical;
      background: #121f22;
      color: var(--text);
      border: 1px solid var(--line);
      border-radius: 18px;
      padding: 18px;
      font-size: 18px;
      line-height: 1.55;
      font-family: ui-monospace, SFMono-Regular, Consolas, monospace;
    }}

    .actions {{
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin: 14px 0;
    }}

    .meta {{
      color: var(--muted);
      font-size: 17px;
      line-height: 1.5;
    }}

    .suspects {{
      margin-top: 18px;
      padding-top: 16px;
      border-top: 1px solid var(--line);
    }}

    .suspects a {{
      padding: 7px 11px;
      margin: 4px;
      background: rgba(180,91,70,0.20);
      border-color: rgba(180,91,70,0.55);
    }}

    .floating-nav {{
      position: fixed;
      left: 50%;
      bottom: 18px;
      transform: translateX(-50%);
      display: flex;
      gap: 10px;
      background: rgba(32, 45, 49, 0.96);
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 10px;
      box-shadow: 0 18px 48px rgba(0,0,0,0.35);
      z-index: 999;
    }}

    @media (max-width: 980px) {{
      body {{ padding: 14px; }}
      .top {{ display: block; }}
      .grid {{ grid-template-columns: 1fr; }}
      textarea {{ min-height: 58vh; }}
      .floating-nav {{
        width: calc(100% - 24px);
        overflow-x: auto;
        justify-content: flex-start;
      }}
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="top">
      <div>
        <h1>Review OCR Text</h1>
        <div class="meta">PDF: <b>{_html_escape(pdf_name)}</b> · Page <b>{page}</b> / {max_page}</div>
      </div>
      <div class="actions">
        <a href="/">Back</a>
        <a href="/review-concepts?pdf={quote(pdf_name)}">Review concepts</a>
        <a href="/study?pdf={quote(pdf_name)}">Study</a>
      </div>
    </div>

    <div class="actions">
      <a href="/review-ocr-text?pdf={quote(pdf_name)}&page={previous_page}">← Previous</a>
      <a href="/review-ocr-text?pdf={quote(pdf_name)}&page={next_page}">Next →</a>
      <a href="/review-ocr-text/rebuild?pdf={quote(pdf_name)}">Rebuild course + study</a>
    </div>

    <div class="grid">
      <section class="panel">
        <h2>Source page</h2>
        {image_html}
      </section>

      <section class="panel">
        <h2>Editable OCR text</h2>
        <form method="post" action="/review-ocr-text/save">
          <input type="hidden" name="pdf" value="{_html_escape(pdf_name)}">
          <input type="hidden" name="page" value="{page}">
          <textarea name="text">{_html_escape(current_text)}</textarea>
          <div class="actions">
            <button type="submit">Save page correction</button>
            <a href="/review-ocr-text?pdf={quote(pdf_name)}&page={page}">Reload</a>
          </div>
        </form>

        <div class="suspects">
          <h3>Suspicious pages</h3>
          <p class="meta">Primele pagini unde OCR-ul pare suspect.</p>
          {suspicious_nav if suspicious_nav else '<p class="meta">No suspicious pages detected.</p>'}
        </div>
      </section>
    </div>
  </div>

  <nav class="floating-nav">
    <a href="/review-ocr-text?pdf={quote(pdf_name)}&page={previous_page}">← Prev</a>
    <a href="/review-ocr-text?pdf={quote(pdf_name)}&page={next_page}">Next →</a>
    <a href="/review-concepts?pdf={quote(pdf_name)}">Concepts</a>
    <a href="/study?pdf={quote(pdf_name)}">Study</a>
  </nav>
</body>
</html>
"""

    return HTMLResponse(html_doc)


@app.post("/review-ocr-text/save")
def save_ocr_text_page(
    pdf: str = Form(...),
    page: int = Form(...),
    text: str = Form(...),
):
    from datetime import datetime, timezone
    from fastapi.responses import HTMLResponse, RedirectResponse
    from urllib.parse import quote
    import traceback

    try:
        pdf_name = _safe_pdf_name(pdf)
        output_dir = _output_dir_for_pdf_name(pdf_name)
        pages = _load_ocr_review_pages(output_dir)

        if not pages:
            return HTMLResponse("<h1>No OCR pages found</h1>", status_code=404)

        changed = False

        for item in pages:
            if int(item["page_number"]) == int(page):
                item["text"] = str(text or "").strip()
                changed = True
                break

        if not changed:
            return HTMLResponse(f"<h1>Page not found: {page}</h1>", status_code=404)

        overrides_path = output_dir / "ocr_page_text_overrides.json"
        overrides = _load_json_file(
            overrides_path,
            {
                "version": "1.0",
                "pages": {},
            },
        )

        overrides.setdefault("pages", {})[str(page)] = {
            "text": str(text or "").strip(),
            "source": "manual_ui",
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }

        _save_json_file(overrides_path, overrides)
        _write_ocr_review_pages(output_dir, pages)

        return RedirectResponse(
            f"/review-ocr-text?pdf={quote(pdf_name)}&page={int(page)}",
            status_code=303,
        )

    except Exception:
        error = traceback.format_exc()
        return HTMLResponse(
            f"""
            <h1>Save OCR text failed</h1>
            <pre style="white-space: pre-wrap; background:#111; color:#f6ead7; padding:16px; border-radius:12px;">{_html_escape(error)}</pre>
            <p><a href="/">Back</a></p>
            """,
            status_code=500,
        )


@app.get("/review-ocr-text/rebuild")
def rebuild_after_ocr_text_review(pdf: str = ""):
    from fastapi.responses import HTMLResponse
    import subprocess
    import sys
    import traceback
    from urllib.parse import quote

    try:
        pdf_name = _safe_pdf_name(pdf)
        output_dir = _output_dir_for_pdf_name(pdf_name)
        pdf_path = PROJECT_ROOT / "data" / "input" / pdf_name
        course_html = output_dir / "course.cleaned.html"

        steps = [
            [
                sys.executable,
                str(PROJECT_ROOT / "services" / "api" / "ocr_course_builder.py"),
                str(output_dir),
                "--pdf-name",
                pdf_name,
                "--min-page",
                "15",
                "--pages-per-lesson",
                "2",
                "--max-lessons",
                "260",
            ],
            [
                sys.executable,
                str(PROJECT_ROOT / "services" / "api" / "html_exporter.py"),
                str(output_dir / "course.cleaned.md"),
            ],
            [
                sys.executable,
                str(PROJECT_ROOT / "services" / "api" / "course_nav_injector.py"),
                str(course_html),
                pdf_name,
            ],
            [
                sys.executable,
                str(PROJECT_ROOT / "services" / "api" / "study_quiz_builder.py"),
                str(output_dir),
                "--min-page",
                "15",
                "--max-per-lesson",
                "3",
                "--max-total",
                "500",
            ],
            [
                sys.executable,
                str(PROJECT_ROOT / "services" / "api" / "ocr_corrections_engine.py"),
                "apply-titles",
                str(output_dir),
            ],
        ]

        logs = []

        for step in steps:
            result = subprocess.run(
                step,
                cwd=str(PROJECT_ROOT),
                text=True,
                capture_output=True,
                encoding="utf-8",
                errors="replace",
            )

            logs.append("$ " + " ".join(step))
            logs.append(result.stdout)

            if result.stderr:
                logs.append("STDERR:")
                logs.append(result.stderr)

            if result.returncode != 0:
                raise RuntimeError("\n".join(logs))

        state = output_dir / "study_state.json"

        if state.exists():
            state.unlink()

        log_text = "\n".join(logs)

        return HTMLResponse(
            f"""
            <h1>Rebuild complete</h1>
            <p>OCR text corrections were applied to course and study.</p>
            <p>
              <a href="/review-ocr-text?pdf={quote(pdf_name)}">Back to OCR Review</a>
              · <a href="/review-concepts?pdf={quote(pdf_name)}">Review Concepts</a>
              · <a href="/study?pdf={quote(pdf_name)}">Study</a>
            </p>
            <pre style="white-space: pre-wrap; background:#111; color:#f6ead7; padding:16px; border-radius:12px;">{_html_escape(log_text)}</pre>
            """
        )

    except Exception:
        error = traceback.format_exc()
        return HTMLResponse(
            f"""
            <h1>Rebuild failed</h1>
            <pre style="white-space: pre-wrap; background:#111; color:#f6ead7; padding:16px; border-radius:12px;">{_html_escape(error)}</pre>
            """,
            status_code=500,
        )
'''

    text += route

path.write_text(text, encoding="utf-8")
print("OK: Review OCR Text UI added.")
