from pathlib import Path
import re

path = Path("services/api/study_quiz_builder.py")
text = path.read_text(encoding="utf-8")

# Add engine cycles as a topic before the existing topic rules.
if '("engine cycles", ["diesel cycle"' not in text:
    text = text.replace(
        "TOPIC_RULES = [\n",
        '''TOPIC_RULES = [
    ("engine cycles", ["diesel cycle", "practical cycle", "indicator diagram", "constant pressure", "constant volume", "adiabatic", "heat rejected", "ideal efficiency"]),
''',
    )

# Improve marine diesel topic matching.
text = text.replace(
    '("marine diesel engines", ["diesel engine", "motor ship", "propulsion", "bore", "stroke"]),',
    '("marine diesel engines", ["diesel engine", "reciprocating engine", "motor ship", "merchant motor ship", "propulsion", "bore", "stroke"]),',
)

# Replace is_generic_title.
text = re.sub(
    r"def is_generic_title\(title: str\) -> bool:\n.*?\n\n\ndef split_sentences",
    '''def is_generic_title(title: str) -> bool:
    value = normalize_key(title)

    if not value:
        return True

    if "pounder" in value and "marine diesel engines" in value:
        return True

    if "marine diesel engines and gas turbines" in value:
        return True

    return value in GENERIC_TITLES or value.startswith("introduction ")


def split_sentences''',
    text,
    flags=re.DOTALL,
)

# Replace sentence_is_bad.
text = re.sub(
    r"def sentence_is_bad\(sentence: str\) -> bool:\n.*?\n\n\ndef technical_score",
    '''def sentence_is_bad(sentence: str) -> bool:
    value = sentence.lower().strip()

    for pattern in BAD_SENTENCE_PATTERNS:
        if re.search(pattern, value):
            return True

    bad_fragments = [
        "generated by voila",
        "mode: source language",
        "text status:",
        "source:",
        "isbn",
        "copyright",
        "all rights reserved",
        "pounder’s marine diesel engines and gas turbines",
        "pounder's marine diesel engines and gas turbines",
        "pressure tdc volume",
        "tdc volume bdc",
        "volume bdc",
    ]

    if any(fragment in value for fragment in bad_fragments):
        return True

    # Reject sentences that are mostly figure labels / page headers.
    words = re.findall(r"[A-Za-z]{3,}", sentence)

    if len(words) <= 5 and any(marker in value for marker in ["tdc", "bdc", "volume", "pressure"]):
        return True

    return False


def technical_score''',
    text,
    flags=re.DOTALL,
)

# Replace infer_concept_title.
text = re.sub(
    r"def infer_concept_title\(lesson_title: str, sentence: str\) -> str:\n.*?\n\n\ndef make_question",
    '''def infer_concept_title(lesson_title: str, sentence: str) -> str:
    title = normalize_space(lesson_title)
    lower = normalize_key(sentence)

    if "term" in lower and "reciprocating engine" in lower:
        return "marine diesel engines"

    if "diesel cycle" in lower or "indicator diagram" in lower:
        return "engine cycles"

    for topic, keywords in TOPIC_RULES:
        if any(keyword in lower for keyword in keywords):
            return topic

    if title and not is_generic_title(title):
        return title.title() if title.isupper() else title

    return "technical fundamentals"


def make_question''',
    text,
    flags=re.DOTALL,
)

# Replace make_question.
text = re.sub(
    r"def make_question\(sentence: str, concept_title: str\) -> tuple\[str, str\]:\n.*?\n\n\ndef lesson_passes_page_filter",
    '''def make_question(sentence: str, concept_title: str) -> tuple[str, str]:
    lower = sentence.lower()
    subject = concept_title

    if "term" in lower and "used to describe" in lower:
        return (
            f"How does the source define {subject}?",
            "definition",
        )

    if "ideal efficiency" in lower and "cycle" in lower:
        return (
            "What does the source state about the ideal efficiency of the cycle?",
            "technical_fact",
        )

    if "heat is rejected" in lower and "constant volume" in lower:
        return (
            "How is heat rejected in the described engine cycle?",
            "cycle_process",
        )

    consists_match = re.search(
        r"^(.{8,90}?)\\s+(?:consists|consist)\\s+of\\s+(.+)$",
        sentence,
        flags=re.IGNORECASE,
    )

    if consists_match:
        detected_subject = normalize_space(consists_match.group(1))
        return (
            f"What does the source say {detected_subject} consists of?",
            "components",
        )

    used_match = re.search(
        r"^(.{8,100}?)\\s+(?:is|are|can be|may be)?\\s*used\\s+(?:to|for)\\s+(.+)$",
        sentence,
        flags=re.IGNORECASE,
    )

    if used_match:
        detected_subject = normalize_space(used_match.group(1))
        detected_lower = detected_subject.lower()

        bad_subject_starts = (
            "today ",
            "the term",
            "this ",
            "these ",
            "it ",
            "in ",
            "when ",
            "where ",
        )

        if detected_lower.startswith(bad_subject_starts):
            detected_subject = subject

        return (
            f"What is the purpose of {detected_subject} according to the source?",
            "purpose",
        )

    if "designed to" in lower or "intended to" in lower:
        return (
            f"What function or purpose is described for {subject}?",
            "purpose",
        )

    if "should" in lower or "must" in lower or "required" in lower or "requires" in lower:
        return (
            f"What requirement or recommended action does the source state for {subject}?",
            "requirement",
        )

    if "prevent" in lower or "prevents" in lower or "avoid" in lower:
        return (
            "What problem is prevented or avoided according to the source?",
            "prevention",
        )

    if "because" in lower or "therefore" in lower or "so that" in lower or "in order to" in lower:
        return (
            f"What cause, reason, or result does the source describe for {subject}?",
            "cause_effect",
        )

    if "when" in lower or "if" in lower or "during" in lower:
        return (
            f"Under what condition or operating situation does the source describe {subject}?",
            "condition",
        )

    return (
        f"What technical point does the source state about {subject}?",
        "technical_fact",
    )


def lesson_passes_page_filter''',
    text,
    flags=re.DOTALL,
)

# Version labels.
text = text.replace("study_quiz_builder_v0.3.2_source_only", "study_quiz_builder_v0.3.3_source_only")
text = text.replace('"version": "0.3.2"', '"version": "0.3.3"')
text = text.replace('"generator": "study_quiz_builder_v0.3.2"', '"generator": "study_quiz_builder_v0.3.3"')

path.write_text(text, encoding="utf-8")
print("OK: study_quiz_builder.py patched to v0.3.3.")
